# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 440)
        icon = QtGui.QIcon.fromTheme("applications-science")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setMinimumSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.verticalLayout.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stopButton.setIcon(icon)
        self.stopButton.setIconSize(QtCore.QSize(24, 24))
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.quitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quitButton.setMinimumSize(QtCore.QSize(40, 40))
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.quitButton.setIcon(icon)
        self.quitButton.setIconSize(QtCore.QSize(24, 24))
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout.addWidget(self.quitButton)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.graphicsView = GraphicsLayoutWidget(parent=self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 50)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "microPyGraph"))
        self.playButton.setToolTip(_translate("MainWindow", "Start [P]"))
        self.playButton.setShortcut(_translate("MainWindow", "P"))
        self.stopButton.setToolTip(_translate("MainWindow", "Stop [S]"))
        self.stopButton.setShortcut(_translate("MainWindow", "S"))
        self.quitButton.setToolTip(_translate("MainWindow", "Quit [Ctrl+Q]"))
        self.quitButton.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
from pyqtgraph import GraphicsLayoutWidget
